"""initial schema

Revision ID: a6a411539295
Revises: 
Create Date: 2026-06-16 00:16:30.868356

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6a411539295'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.UniqueConstraint('employee_code', name=op.f('uq_employees_employee_code')),
    sa.UniqueConstraint('email', name=op.f('uq_employees_email')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_country_code'), 'employees', ['country_code'], unique=False)
    op.create_index(op.f('ix_employees_currency_code'), 'employees', ['currency_code'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['from_currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['to_currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'as_of', name='uq_fx_pair_asof')
    )
    op.create_index(op.f('ix_fx_rates_from_currency'), 'fx_rates', ['from_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fx_rates_from_currency'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_currency_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_country_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('currencies')
    op.drop_table('countries')
    # ### end Alembic commands ###
